# version: "3"
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#       - "3000:3000"
#     volumes:
#       - /app/node_modules
#       - .:/app
#   tests:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     volumes:
#       - /app/node_modules
#       - .:/app
#     command: ["npm", "run", "test"]
#   production:
#     build:
#       context: .
#       dockerfile: Dockerfile.prod
#     ports:
#       - "3000:3000"
#     volumes:
#       - /app/node_modules
#       - .:/app



version: '3' 
services: 
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_PASSWORD=postgres_password
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432
    ports:
      - "3000:3000"